2018-03-02 21:21:48,631 ERROR: Exception on /login [GET] [in /home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ff7f/Desktop/microblog/app/routes.py", line 79, in login
    return render_template('login.html', title='Логырование', form=form)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ff7f/Desktop/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ff7f/Desktop/microblog/app/templates/base.html", line 24, in top-level template code
    <a href="{{ url_for('forcss') }}">"CSS experience"</a>
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'forcss'. Did you mean 'for_css' instead?
2018-03-02 21:22:29,060 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:36:02,646 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:37:24,035 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:37:45,572 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:38:42,419 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:39:43,208 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:42:36,781 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:42:59,851 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:43:36,214 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:43:58,186 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:44:08,228 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:46:31,052 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:49:14,426 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:49:36,068 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:51:15,473 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:51:33,946 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:52:00,560 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:53:34,668 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:54:42,575 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:54:44,030 ERROR: Exception on /forcss [GET] [in /home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ff7f/Desktop/microblog/app/routes.py", line 176, in for_css
    return render_template('forcss.html', title='CSS exp')
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ff7f/Desktop/microblog/app/templates/forcss.html", line 8, in top-level template code
    <a href="{{ url_for('forcss') }}">Обновить  ЭТУ страницу</a>
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'forcss'. Did you mean 'for_css' instead?
2018-03-02 21:54:54,345 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:56:48,202 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:56:59,242 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:57:11,772 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 21:58:44,448 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 22:00:49,922 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 22:02:52,097 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 22:03:31,294 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 22:04:09,178 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 22:05:28,981 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 22:05:48,640 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 22:06:02,853 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 22:07:12,556 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-02 22:08:25,750 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
