2018-03-07 21:45:29,775 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-07 21:46:13,018 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-07 21:51:06,288 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-07 22:31:01,145 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-07 22:35:25,422 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-07 22:35:59,271 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-11 22:48:55,180 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-11 23:11:01,191 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-11 23:11:36,215 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-11 23:11:55,133 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-11 23:13:06,418 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-11 23:17:57,412 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-11 23:18:12,945 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-11 23:21:09,714 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-11 23:23:18,047 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-11 23:31:29,698 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-11 23:33:12,397 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-11 23:34:27,144 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-11 23:35:10,837 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-11 23:35:37,994 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-11 23:37:06,755 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-11 23:38:41,505 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-22 21:10:39,374 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-22 21:43:53,513 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-22 21:44:41,404 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-22 21:46:29,454 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-22 21:47:24,201 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-22 21:50:08,546 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-22 21:51:01,053 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-23 21:02:27,047 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-23 21:02:33,142 ERROR: Exception on /index [GET] [in /home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ff7f/Desktop/microblog/app/routes.py", line 27, in index
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2018-03-23 21:03:30,326 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-23 21:03:32,976 ERROR: Exception on /index [GET] [in /home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ff7f/Desktop/microblog/app/routes.py", line 36, in index
    return render_template("index.html", title='Index page', posts=posts.items,next_url=next_url, prev_url=prev_url)
UnboundLocalError: local variable 'prev_url' referenced before assignment
2018-03-23 21:04:45,895 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:36]
2018-03-23 21:04:48,384 ERROR: Exception on /index [GET] [in /home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ff7f/Desktop/microblog/app/routes.py", line 36, in index
    return render_template("index.html", title='Index page', posts=posts.items,next_url=next_url, prev_url=prev_url)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ff7f/Desktop/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ff7f/Desktop/microblog/app/templates/base.html", line 38, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ff7f/Desktop/microblog/app/templates/index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
